// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Muscat.Infrastructure.Migrations.Entries
{
    [DbContext(typeof(MuscatDbContext))]
    partial class MuscatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Muscat.Core.Domains.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("_createdDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(3);

                    b.Property<string>("_uri")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Uri")
                        .HasColumnOrder(1)
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("_modifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedDate")
                        .HasColumnOrder(4);

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasColumnOrder(2)
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasAlternateKey("_name");

                    b.ToTable("Domains", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
